# Generated by Django 5.2.1 on 2025-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=20)),
                ('Edad', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('objetivo', models.CharField(choices=[('Pérdida de peso', 'Pérdida de peso'), ('Ganancia muscular', 'Ganancia muscular'), ('Resistencia', 'Resistencia'), ('Mantenimiento', 'Mantenimiento')], default='Mantenimiento', max_length=20)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('trainer', 'trainer'), ('nutricionista', 'nutricionista')], default='user', max_length=13)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('recuperarcontraseña', models.CharField(blank=True, max_length=128, null=True)),
                ('token', models.CharField(blank=True, max_length=128, null=True)),
                ('token_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
