# Generated by Django 5.2 on 2025-08-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPersonalUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_personal_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('aporte_muscular', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=200)),
                ('Edad', models.DateField(blank=True, null=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('trainer', 'trainer'), ('nutricionista', 'nutricionista')], default='user', max_length=13)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('recuperarcontrasena', models.CharField(blank=True, max_length=128, null=True)),
                ('token', models.CharField(blank=True, max_length=128, null=True)),
                ('token_expiracion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ejercicios', models.PositiveSmallIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.rutina')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('rutina', 'ejercicio')},
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='rutinas', through='landingpage.RutinaEjercicio', to='landingpage.ejercicio'),
        ),
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('objetivo', models.CharField(blank=True, choices=[('weight_loss', 'Pérdida de peso'), ('muscle_gain', 'Ganancia muscular'), ('endurance', 'Resistencia'), ('maintenance', 'Mantenimiento')], default='maintenance', max_length=20, null=True)),
                ('id_usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='landingpage.usuarios')),
            ],
            options={
                'db_table': 'datos_usuario',
                'managed': True,
            },
        ),
    ]
