# Generated by Django 5.2 on 2025-08-08 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='edad',
            field=models.DateField(blank=True, default=datetime.date(200, 1, 1), null=True),
        ),
    ]
