# Generated by Django 5.2.1 on 2025-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPersonalUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_anterior', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_personal_usuario',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Edad',
            field=models.IntegerField(),
        ),
    ]
