# Generated by Django 5.2 on 2025-08-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_datosusuario_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
