# Generated by Django 5.2.1 on 2025-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_historialpersonalusuario_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='objetivo',
            field=models.CharField(choices=[('weight_loss', 'Pérdida de peso'), ('muscle_gain', 'Ganancia muscular'), ('endurance', 'Resistencia'), ('maintenance', 'Mantenimiento')], default='maintenance', max_length=20),
        ),
    ]
